### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by zghwi** [icositetrachoron-programmer/wasm-canvas#1]
hi programmeruser2
I would like to try your WebAssembly Canvas, so I forked it to repl.it.
I went to the shell, and look:
![image](https://user-images.githubusercontent.com/73612690/107844578-33d92180-6ddd-11eb-9c3f-d6112efbd614.png)

Even on my machine:
![image](https://user-images.githubusercontent.com/73612690/107844730-badac980-6dde-11eb-83c1-6ea0408fd92b.png)

I don't know why, I'll be happy when you fix it :)
have a great day

**Comment by programmeruser2** [comment]
Should be fixed now, make complains if you use spaces instead of tabs for indentation.
Make sure you have clang installed: `sudo apt install clang-11`

**Comment by zghwi** [comment]
yeah I have clang, thank you
